# Generated by Django 4.2.7 on 2023-11-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_scrapeprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('translator', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_price', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_type', models.CharField(blank=True, max_length=100, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('first_print_year', models.CharField(blank=True, max_length=50, null=True)),
                ('print_number', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scrapedurl',
            name='is_scrapped',
            field=models.BooleanField(default=False),
        ),
    ]
