# Generated by Django 4.2.7 on 2023-11-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
