# Generated by Django 4.2.7 on 2023-11-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_book_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
