# Generated by Django 4.2.7 on 2023-11-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_book_original_language_book_original_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_set',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
