# Generated by Django 4.2.7 on 2023-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_book_book_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sensibility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
