# Generated by Django 4.2.7 on 2023-11-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_book_sensibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
