# Generated by Django 4.2.7 on 2023-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_alter_book_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
    ]
