# Generated by Django 4.2.7 on 2023-12-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_book_error_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='error_count',
        ),
        migrations.AddField(
            model_name='scrapedurl',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
    ]
