# Generated by Django 4.2.7 on 2023-12-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_remove_book_error_count_scrapedurl_error_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
