# Generated by Django 4.2.7 on 2023-12-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_book_others'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_set',
        ),
        migrations.RemoveField(
            model_name='book',
            name='first_print_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='paper_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='print_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sensibility',
        ),
        migrations.RemoveField(
            model_name='book',
            name='size',
        ),
    ]
